### ISSUE TITLE
[BUG] hi!, idk why but the variant seems to doesnt has a recipe 

### ISSUE THREAD

**Issue by raffale1e** [xanthian/VariantChiseledBookshelves#1]
ill give u some screen
![Screenshot 2024-02-21 180628](https://github.com/xanthian/VariantChiseledBookshelves/assets/160768115/58581b4c-b0da-4220-93d7-2f80d19c764c)

**Comment by xanthian** [comment]
Version?
Fabric/Forge?
Modlist?

**Comment by raffale1e** [comment]
so version : 1.20.2
im on fabric
for the mod list ill give u some screens
![image](https://github.com/xanthian/VariantChiseledBookshelves/assets/160768115/2cde751b-3338-40b8-86db-7fe4d2e692be)
![image](https://github.com/xanthian/VariantChiseledBookshelves/assets/160768115/408675bd-4173-449d-a311-59c53974d885)
![image](https://github.com/xanthian/VariantChiseledBookshelves/assets/160768115/cd874c25-b293-4b71-843f-0a050116da75)
![image](https://github.com/xanthian/VariantChiseledBookshelves/assets/160768115/7a5d1f5c-b5a0-456b-8b31-a33c74bcb747)
so sorry for the late response

**Comment by xanthian** [comment]
> so version : 1.20.2 im on fabric for the mod list ill give u some screens ![image](https://private-user-images.githubusercontent.com/160768115/306990177-2cde751b-3338-40b8-86db-7fe4d2e692be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MDEzNTUsIm5iZiI6MTcwODgwMTA1NSwicGF0aCI6Ii8xNjA3NjgxMTUvMzA2OTkwMTc3LTJjZGU3NTFiLTMzMzgtNDBiOC04NmRiLTdmZTRkMmU2OTJiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQxODU3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGRlZThhODllMTNkMTQ3Mjg2MDNkYTE5OTQ2NTNmMDA4NTZmMWY1OTYxODdjMzM4MmMyNTA4M2FlOThhY2I0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yBVKJROBqQp0X_ZI4JAefu0zIahCvJvdyYmvMz2q30Y) ![image](https://private-user-images.githubusercontent.com/160768115/306990370-408675bd-4173-449d-a311-59c53974d885.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MDEzNTUsIm5iZiI6MTcwODgwMTA1NSwicGF0aCI6Ii8xNjA3NjgxMTUvMzA2OTkwMzcwLTQwODY3NWJkLTQxNzMtNDQ5ZC1hMzExLTU5YzUzOTc0ZDg4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQxODU3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWVkNGExMmU5ZGEzMDY5ZDIzMmYxOWM5OWUwOWM3ZmFkZGQyNmEzNDFiMzVkOTQxNjFmMDcxZGUyYWM4M2VmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VZJmAWysCasDHpPnsFM142tj2Khyr9xfJgBqRFFQdWQ) ![image](https://private-user-images.githubusercontent.com/160768115/306990512-cd874c25-b293-4b71-843f-0a050116da75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MDEzNTUsIm5iZiI6MTcwODgwMTA1NSwicGF0aCI6Ii8xNjA3NjgxMTUvMzA2OTkwNTEyLWNkODc0YzI1LWIyOTMtNGI3MS04NDNmLTBhMDUwMTE2ZGE3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQxODU3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDFmYmFhNDIyYmUwZGMwNjZlZjM5OTNiOGQ5ZjU2M2I0ZmQ1MWY1ZmQwZGQyMjU0OTU5ZjMxNGU1NmMyZjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9P4jQ1tuzXjx2dNo3cjmrTTMmV829ddJGmYIAM7khC8) ![image](https://private-user-images.githubusercontent.com/160768115/306990595-7a5d1f5c-b5a0-456b-8b31-a33c74bcb747.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MDEzNTUsIm5iZiI6MTcwODgwMTA1NSwicGF0aCI6Ii8xNjA3NjgxMTUvMzA2OTkwNTk1LTdhNWQxZjVjLWI1YTAtNDU2Yi04YjMxLWEzM2M3NGJjYjc0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQxODU3MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWRlMzgwNzVlNGY2Yjk2NmUzMzg1NWI1MGViNjQ0ZWI4NTE3NGJhMmFjYTgwMmQ0YzBhOTIyNzk1MWU3NWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vAJnIy0JBC6K08CUlzvQ5xR70aChceVo4KJyi5I-YTo) so sorry for the late response

Fixed, new versions 1.3.8 uploaded to CF
